"""SQLAlchemy model for the materialized TB culture dataset.

The underlying table contains patient-identifying and clinical information.
Access to this model and any service exposing it must be explicitly authorized.
"""

from datetime import datetime, timezone

from sqlalchemy.dialects.mssql import DATETIME2, TINYINT

from db.database import db


MSSQL_BIGINT = db.BigInteger().with_variant(db.Integer(), "sqlite")
MSSQL_TINYINT = TINYINT().with_variant(db.SmallInteger(), "sqlite")
MSSQL_DATETIME2_3 = DATETIME2(precision=3).with_variant(db.DateTime(), "sqlite")


def _utc_now():
    """Return a naive UTC datetime compatible with SQL Server ``datetime2``."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class TBCultura(db.Model):
    __bind_key__ = "tb"
    __tablename__ = "TBCultura"
    __table_args__ = {"extend_existing": True}

    ID = db.Column(MSSQL_BIGINT, primary_key=True, autoincrement=True)

    # Source columns, in the exact ordinal order of viewTB_Cultura.
    RequestID = db.Column(db.String(26), nullable=False, unique=True)
    EncryptedPatientID = db.Column(db.String(64), nullable=True)
    PatientLocation = db.Column(db.String(5), nullable=True)
    PatientNationalID = db.Column(db.String(26), nullable=True)
    PatientSurname = db.Column(db.String(31), nullable=True)
    PatientFirstName = db.Column(db.String(31), nullable=True)
    PatientDOB = db.Column(db.DateTime, nullable=True)
    PatientDOBType = db.Column(db.String(25), nullable=True)
    PatientHealthcareNo = db.Column(db.String(25), nullable=True)
    PatientHomePhone = db.Column(db.String(20), nullable=True)
    PatientRegisteredDate = db.Column(db.DateTime, nullable=True)
    PatientUUID = db.Column(db.String(50), nullable=True)
    AgeInYears = db.Column(db.Integer, nullable=True)
    AgeInDays = db.Column(db.Integer, nullable=True)
    HL7SexCode = db.Column(db.CHAR(1), nullable=True)
    HL7EthnicGroupCode = db.Column(db.CHAR(3), nullable=True)
    Deceased = db.Column(db.Boolean, nullable=True)
    Newborn = db.Column(db.Boolean, nullable=True)
    HL7PatientClassCode = db.Column(db.CHAR(1), nullable=True)
    SpecimenDateTime = db.Column(db.DateTime, nullable=True)
    LIMSPreReg_RegistrationDateTime = db.Column(db.DateTime, nullable=True)
    LIMSPreReg_ReceivedDateTime = db.Column(db.DateTime, nullable=True)
    LIMSPreReg_RegistrationFacilityCode = db.Column(db.String(15), nullable=True)
    RegisteredDateTime = db.Column(db.DateTime, nullable=True)
    ReceivedDateTime = db.Column(db.DateTime, nullable=True)
    AnalysisDateTime = db.Column(db.DateTime, nullable=True)
    AuthorisedDateTime = db.Column(db.DateTime, nullable=True)
    AdmitAttendDateTime = db.Column(db.DateTime, nullable=True)
    FirstPrinted = db.Column(db.DateTime, nullable=True)
    LIMSRejectionCode = db.Column(db.String(10), nullable=True)
    LIMSRejectionDesc = db.Column(db.String(250), nullable=True)
    SolidCultureResult = db.Column(db.String(80), nullable=True)
    SolidCultureResultDate = db.Column(db.String(80), nullable=True)
    LiquidCultureResult = db.Column(db.String(80), nullable=True)
    LiquidCultureResultDate = db.Column(db.String(80), nullable=True)
    InterpretedLiquidCultureResult = db.Column(db.String(80), nullable=True)
    InterpretedSolidCultureResult = db.Column(db.String(80), nullable=True)
    InterpretedCultureResultDate = db.Column(db.String(80), nullable=True)
    TBIDResult = db.Column(db.String(80), nullable=True)
    TBIDResultDate = db.Column(db.String(80), nullable=True)
    LPAPanelCode = db.Column(db.String(3), nullable=True)
    LPAIsoniazidResult = db.Column(db.String(80), nullable=True)
    LPAComplexMTBResult = db.Column(db.String(80), nullable=True)
    LPARifampicinResult = db.Column(db.String(80), nullable=True)
    LPAResultDate = db.Column(db.String(80), nullable=True)
    LPA2PanelCode = db.Column(db.String(4), nullable=True)
    LPA2FluoroquinoloneResult = db.Column(db.String(80), nullable=True)
    LPA2KACResult = db.Column(db.String(80), nullable=True)
    LPA2KACVResult = db.Column(db.String(80), nullable=True)
    LPA2KCVResult = db.Column(db.String(80), nullable=True)
    LPA2ComplexMTBResult = db.Column(db.String(80), nullable=True)
    LPA2LowLevelKanamycinResult = db.Column(db.String(80), nullable=True)
    LPA2ResultDate = db.Column(db.String(80), nullable=True)
    LPACMResult = db.Column(db.String(80), nullable=True)
    LPACMResultDate = db.Column(db.String(80), nullable=True)
    TSAPanelCode = db.Column(db.String(3), nullable=True)
    TSAEthambutolResult = db.Column(db.String(80), nullable=True)
    TSAIsoniazidResult = db.Column(db.String(80), nullable=True)
    TSAPyrazinamideResult = db.Column(db.String(80), nullable=True)
    TSARifampicinResult = db.Column(db.String(80), nullable=True)
    TSAStreptomycinResult = db.Column(db.String(80), nullable=True)
    TSAResultDate = db.Column(db.String(80), nullable=True)
    TSA2PanelCode = db.Column(db.String(4), nullable=True)
    TSA2AmikacinResult = db.Column(db.String(80), nullable=True)
    TSA2BedaquilineResult = db.Column(db.String(80), nullable=True)
    TSA2ClofazimineResult = db.Column(db.String(80), nullable=True)
    TSA2CapreomycinResult = db.Column(db.String(80), nullable=True)
    TSA2EthionamideResult = db.Column(db.String(80), nullable=True)
    TSA2KanamycinResult = db.Column(db.String(80), nullable=True)
    TSA2LevofloxacinResult = db.Column(db.String(80), nullable=True)
    TSA2LinezolidResult = db.Column(db.String(80), nullable=True)
    TSA2MoxifloxacinResult = db.Column(db.String(80), nullable=True)
    TSA2OfloxacinResult = db.Column(db.String(80), nullable=True)
    TSA2ProthionamideResult = db.Column(db.String(80), nullable=True)
    TSA2ResultDate = db.Column(db.String(80), nullable=True)
    FinalLJCultureResult = db.Column(db.String(80), nullable=True)
    FinalLJResultDate = db.Column(db.String(80), nullable=True)
    FinalMGITCultureResult = db.Column(db.String(80), nullable=True)
    FinalMGITResultDate = db.Column(db.String(80), nullable=True)
    DateTimeStamp = db.Column(db.DateTime, nullable=True)
    Versionstamp = db.Column(db.String(30), nullable=True)
    LIMSDateTimeStamp = db.Column(db.DateTime, nullable=True)
    LIMSVersionstamp = db.Column(db.String(30), nullable=True)
    LOINCPanelCode = db.Column(db.String(10), nullable=True)
    HL7PriorityCode = db.Column(db.CHAR(1), nullable=True)
    CollectionVolume = db.Column(db.Float(precision=53), nullable=True)
    LIMSPointOfCareDesc = db.Column(db.String(50), nullable=True)
    RequestTypeCode = db.Column(db.String(3), nullable=True)
    ICD10ClinicalInfoCodes = db.Column(db.String(50), nullable=True)
    ClinicalInfo = db.Column(db.String(250), nullable=True)
    HL7SpecimenSourceCode = db.Column(db.String(10), nullable=True)
    LIMSSpecimenSourceCode = db.Column(db.String(10), nullable=True)
    LIMSSpecimenSourceDesc = db.Column(db.String(50), nullable=True)
    HL7SpecimenSiteCode = db.Column(db.String(10), nullable=True)
    LIMSSpecimenSiteCode = db.Column(db.String(10), nullable=True)
    LIMSSpecimenSiteDesc = db.Column(db.String(50), nullable=True)
    WorkUnits = db.Column(db.Float(precision=53), nullable=True)
    CostUnits = db.Column(db.Float(precision=53), nullable=True)
    HL7SectionCode = db.Column(db.String(3), nullable=True)
    HL7ResultStatusCode = db.Column(db.CHAR(1), nullable=True)
    RegisteredBy = db.Column(db.String(250), nullable=True)
    TestedBy = db.Column(db.String(250), nullable=True)
    AuthorisedBy = db.Column(db.String(250), nullable=True)
    OrderingNotes = db.Column(db.String(250), nullable=True)
    AttendingDoctor = db.Column(db.String(50), nullable=True)
    ReferringRequestID = db.Column(db.String(25), nullable=True)
    Therapy = db.Column(db.String(250), nullable=True)
    LIMSAnalyzerCode = db.Column(db.String(10), nullable=True)
    TargetTimeDays = db.Column(db.Integer, nullable=True)
    TargetTimeMins = db.Column(db.Integer, nullable=True)
    Repeated = db.Column(MSSQL_TINYINT, nullable=True)
    LIMSVendorCode = db.Column(db.String(4), nullable=True)
    TestingLabRequestID = db.Column(db.String(20), nullable=True)
    LIMSFacilityCode = db.Column(db.String(15), nullable=True)
    LIMSFacilityName = db.Column(db.String(50), nullable=True)
    LIMSProvinceName = db.Column(db.String(50), nullable=True)
    LIMSDistrictName = db.Column(db.String(50), nullable=True)
    RequestingFacilityCode = db.Column(db.String(15), nullable=True)
    RequestingFacilityNationalCode = db.Column(db.String(15), nullable=True)
    RequestingFacilityName = db.Column(db.String(50), nullable=True)
    RequestingProvinceName = db.Column(db.String(50), nullable=True)
    RequestingDistrictName = db.Column(db.String(50), nullable=True)
    ReceivingFacilityCode = db.Column(db.String(10), nullable=True)
    ReceivingFacilityName = db.Column(db.String(50), nullable=True)
    ReceivingProvinceName = db.Column(db.String(50), nullable=True)
    ReceivingDistrictName = db.Column(db.String(50), nullable=True)
    TestingFacilityCode = db.Column(db.String(10), nullable=True)
    TestingFacilityName = db.Column(db.String(50), nullable=True)
    TestingProvinceName = db.Column(db.String(50), nullable=True)
    TestingDistrictName = db.Column(db.String(50), nullable=True)

    # Target-owned operational columns.
    EPTS = db.Column(db.String(255), nullable=True)
    EPTS_DATETIME = db.Column(db.DateTime, nullable=True)
    SMS_NOTIFICATION = db.Column(db.String(100), nullable=True)
    SMS_NOTIFICATION_DATETIME = db.Column(db.DateTime, nullable=True)
    CreatedAt = db.Column(MSSQL_DATETIME2_3, nullable=False, default=_utc_now)
    UpdatedAt = db.Column(
        MSSQL_DATETIME2_3,
        nullable=False,
        default=_utc_now,
        onupdate=_utc_now,
    )
